# Generated by Django 5.0.6 on 2026-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('SICK', 'Kasallik'), ('FAMILY', 'Oilaviy sabab'), ('COMPETITION', 'Musobaqa / olimpiada'), ('OTHER', 'Boshqa sabab')], max_length=12),
        ),
    ]
