# Generated by Django 5.0.6 on 2026-09-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_moderationincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('CLASS_GENERAL', 'Class general chat'), ('PRIVATE', 'Private chat'), ('TEACHER_STUDENT', 'Teacher-student chat'), ('PARENT_TEACHER', 'Parent-teacher chat'), ('STAFF_GENERAL', 'Staff general chat')], max_length=20),
        ),
    ]
